const skillSet = [
  { 
    type:"Programming Languages",
    skills:[
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },    
    ]
  },
  { 
    type:"Programming Languages",
    skills:[
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },    
    ]
  },
  { 
    type:"Programming Languages",
    skills:[
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },
      {
        name:"React",
        ref:require("../utils/images/react.png")
      },    
    ]
  }]
 
export default skillSet;